export const testimonials = [
  {
    id: 1,
    author: "Vicky Jain",
    content: `You go fly high and capture the world, I will always be your biggest cheerleader. Yashu is my Proud. What an incredible success! To Nailcredibles. From Your Incredible`,
    visible: true,
    position: { x: 390, y: 30 },
    zIndex: 1,
  },
  {
    id: 2,
    author: "Paroksh Jain",
    content: `Yashi, remember when you first started Nailcredibles? You had a spark in your eyes, and now it's a blazing fire! I'm so grateful to have a sister like you. Your journey is a reminder that anything is possible with love and perseverance. Congratulations on 5 incredible years! Keep shining!`,
    visible: true,
    position: { x: 390, y: 30 },
    zIndex: 1,
  },
  {
    id: 3,
    author: "Mom & Dad",
    content: `Laado, 5 years of Nailcredibles is a tremendous achievement! Mom and Dad are overflowing with pride and joy. Your hard work and commitment to your craft are truly inspiring. Keep shining, and never forget that we're always here to support and love you.`,
    visible: true,
    position: { x: 390, y: 30 },
    zIndex: 1,
  },
  {
    id: 4,
    author: "Het Jain",
    content: `Congratulations!!🥳 on completing 5 years of nailcredibles many more years to come of growth, success and fame best wishes ❤️!! Those late nights and early morning countless backache still working and working. Now I know what it feels and creating a brand like nailcredibles nd your success feels like my own. Proud of you !!🫶`,
    visible: true,
    position: { x: 390, y: 30 },
    zIndex: 1,
  },
  {
    id: 5,
    author: "Nayan Shah",
    content: `From starting with zero clients to 5 amazing years as one of the best nail techs—your journey is incredible! 🌟💅 Despite health challenges, you never gave up and proved what true dedication looks like. So proud of you 🤍✨ This is just the beginning—may your success keep soaring! 📈💖`,
    visible: true,
    position: { x: 390, y: 30 },
    zIndex: 1,
  },
  {
    id: 20,
    author: "Darshan Rajput",
    content: `Happy 5 years to the most Nailcredible journey! 💅 Your dedication, creativity, and passion have truly made a mark. You didn’t just build a brand, you nailed it! 😉 I’m so proud of everything you’ve achieved so far. Here’s to many more fabulous years ahead—and I hope the next five bring you even closer to your dream of opening your very own studio! ✨`,
    visible: true,
    position: { x: 390, y: 30 },
    zIndex: 1,
  },
];
