export const testimonials = [
  {
    id: 1,
    author: "Janvi Mehta",
    content:
      "Love how the way my nails turned out.Honestly the amount of work Yashi mam put in for the little details and how creatively she made the designs,it was all worth it.I am literally so obsessed with my nail art😍❤️🤌",
    visible: true,
    position: { x: 390, y: 30 },
    zIndex: 1,
  },
  {
    id: 2,
    author: "Riva Jain",
    content: `She is the first person i ever got my nails done from and trust meee she's the best when it comes to nails and really on point and accurate her work is very cleannn and perfect she can literally pull up any design u show her😂`,
    visible: true,
    position: { x: 390, y: 30 },
    zIndex: 1,
  },
  {
    id: 3,
    author: "Soniya Raikar",
    content: `Yashi is extremely creative and talented person. She is good at her nail art and is perfect in building the apt shape for nail extension. Extremely passionate about her profession and is a very friendly person.`,
    visible: true,
    position: { x: 390, y: 30 },
    zIndex: 1,
  },
  {
    id: 4,
    author: "Heena Rathod",
    content: `Yashi's nail art definitely reflects her love for it. I wait to go to her every month just because she make my nails look extremely beautiful. She is very creative and loves to try new things! Way to go, babe! You are truly an artist in real sense!😍`,
    visible: true,
    position: { x: 390, y: 30 },
    zIndex: 1,
  },
  {
    id: 5,
    author: "Brisa Shah",
    content: `Absolutely loved the nails done by Yashi! Received sooo many compliments on them as well. The entire experience was made very smooth and comfortable with her and the ideas she would have for the nails were amazing as well.`,
    visible: true,
    position: { x: 390, y: 30 },
    zIndex: 1,
  },
  {
    id: 6,
    author: "Fatema Abizer",
    content: `This is the first time I got extensions and Yashi did an amazing job. She is so warm as a person and extremely professional and talented with her work. I had no word of mouth nor any reference ,just Google reviews and am glad I chose her! Thanks Yashi for making my first experience the best❤️`,
    visible: true,
    position: { x: 390, y: 30 },
    zIndex: 1,
  },
  {
    id: 7,
    author: "Nirali Rajput",
    content: `She has easily become my go to whenever I want to get my nails done. She is professional yet warm and can be trusted with your precious nails. Each time I have a great experience and leave her place happy and obsessed with my nails🥰`,
    visible: true,
    position: { x: 390, y: 30 },
    zIndex: 1,
  },
  {
    id: 8,
    author: "Bhakti Dave",
    content: `She is the sweetest person I have ever meet❤️ Her work is just an amazing😍😍😍In very early age she have gone to the top😍Would like to be her client once again very soon...!❤️`,
    visible: true,
    position: { x: 390, y: 30 },
    zIndex: 1,
  },
  {
    id: 9,
    author: "Nidhi Sharma",
    content: `She is my go to person for nails! She is a young girl who is ambitious and very creative in her work. With amazing finishing she gives your nails a better look! I would recommend all the people out there to definitely go to her for nails and I’m sure you will never go to anyone else.`,
    visible: true,
    position: { x: 390, y: 30 },
    zIndex: 1,
  },
  {
    id: 10,
    author: "Pankti Jadia",
    content: `The Best Nail Artist in town! And even a Better person at heart! Never a dull moment with Yashi while getting your nails done! ❤️❤️`,
    visible: true,
    position: { x: 390, y: 30 },
    zIndex: 1,
  },
  {
    id: 11,
    author: "Vrunda Upadhayay",
    content: `An absolute genius when it comes to nails, colour, design,she has it all and much more!❤️`,
    visible: true,
    position: { x: 390, y: 30 },
    zIndex: 1,
  },
  {
    id: 12,
    author: "Darshan Rajput",
    content: `Happy 5 years to the most Nailcredible journey! Your dedication, creativity, and passion have truly made a mark. You didn't just build a brand, you nailed it!😉 Here's to many more fabulous years ahead!✨`,
    visible: true,
    position: { x: 390, y: 30 },
    zIndex: 1,
  },
];
